-- MySQL Script generated by MySQL Workbench
-- Tue Nov 12 14:34:59 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ShopInternet
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ShopInternet
-- -----------------------------------------------------
DROP DATABASE IF EXISTS `ShopInternet`;
CREATE SCHEMA `ShopInternet` DEFAULT CHARACTER SET UTF8MB4;

USE `ShopInternet` ;

-- -----------------------------------------------------
-- Table `ShopInternet`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShopInternet`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `tel` VARCHAR(20) NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `user_tel_UNIQUE` (`tel` ASC) VISIBLE,
  UNIQUE INDEX `user_email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShopInternet`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShopInternet`.`categories` (
  `categories_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY (`categories_id`),
  UNIQUE INDEX `categories_id_UNIQUE` (`categories_id` ASC) VISIBLE)
ENGINE = InnoDB;
INSERT INTO `ShopInternet`.`categories` (`name`) 
VALUES ('Phones'), ('Laptops'), ('Teas'), ('Coffe');

-- -----------------------------------------------------
-- Table `ShopInternet`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShopInternet`.`products` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `category_id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `image` VARCHAR(255) NULL ,
  `description` VARCHAR(200) NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY (`product_id`),
  UNIQUE INDEX `product_id_UNIQUE` (`product_id` ASC) VISIBLE,
  INDEX `category_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `category`
    FOREIGN KEY (`category_id`)
    REFERENCES `ShopInternet`.`categories` (`categories_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;
INSERT INTO `ShopInternet`.`products` 
(`category_id`, `name`, `price`, `image`, `description`)
VALUES 
(1, 'Iphone11', 299.99, 'images/phone/Iphone11.webp', 'The revolution of new iPhones released in 2019'),
(1, 'Iphone12', 399.99, 'images/phone/Iphone12.webp', 'The slogan "First, it\'s fast" was released in 2020'),
(1, 'Iphone13', 499.99, 'images/phone/Iphone13.webp', '15th generation iPhone released in 2021'),
(1, 'Iphone14', 599.99, 'images/phone/Iphone14.webp', 'Almost no different from the iphone13 released in 2022'),
(1, 'Iphone15', 699.99, 'images/phone/Iphone15.webp', 'The previous iPhone from Apple was released in 2023'),
(1, 'Iphone16', 799.99, 'images/phone/Iphone16.webp', 'The newest iPhone released in 2024'),
(2, 'Asus TUF Gaming A15', 1499.99, 'images/laptops/Asus TUF Gaming A15.webp', 'Processor: Ryzen 5 7535HS, Video card: GeForce RTX 4050'),
(2, 'Asus TUF Gaming F15', 1299.99, 'images/laptops/Asus TUF Gaming F15.webp', 'Processor: Core i5-12500H, Video card: GeForce RTX 3050'),
(2, 'Lenovo LOQ 15IAX9', 1399.99, 'images/laptops/Lenovo LOQ 15IAX9.webp', 'Processor: Core i5-12450HX, Video card: GeForce RTX 3050'),
(2, 'MSI Thin', 1199.99, 'images/laptops/MSI Thin.webp', 'Processor: Core i5-12450H, Video card: GeForce RTX 3050'),
(3, 'Black tea', 59.99, 'images/teas/Black tea.jpg', 'Classic tea'),
(3, 'Green tea', 59.99, 'images/teas/Green tea.webp', 'Chamomile and raspberry tea'),
(3, 'Lemon tea', 79.99, 'images/teas/Lemon tea.webp', 'Tea with lemon juice'),
(3, 'Herbal tea', 89.99, 'images/teas/Herbal tea.webp', 'Tea with exotic herbs'),
(4, 'Strong coffee', 59.99, 'images/coffee/Strong coffee.webp', 'An invigorating charge of energy'),
(4, 'Regular coffee', 49.99, 'images/coffee/Regular coffee.webp', 'For tasting');

-- -----------------------------------------------------
-- Table `ShopInternet`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShopInternet`.`cart` (
  `cart_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `cost_goods` DECIMAL(10) NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  INDEX `user_idx` (`user_id` ASC) VISIBLE,
  INDEX `goods_idx` (`product_id` ASC) VISIBLE,
  PRIMARY KEY (`cart_id`),
  CONSTRAINT `users`
    FOREIGN KEY (`user_id`)
    REFERENCES `ShopInternet`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `products`
    FOREIGN KEY (`product_id`)
    REFERENCES `ShopInternet`.`products` (`product_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShopInternet`.`admins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShopInternet`.`admins` (
  `admin_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `tel` VARCHAR(20) NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY (`admin_id`),
  UNIQUE INDEX `admin_id_UNIQUE` (`admin_id` ASC) VISIBLE,
  UNIQUE INDEX `admin_email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `admin_tel_UNIQUE` (`tel` ASC) VISIBLE)
ENGINE = InnoDB;
INSERT INTO admins (name, surname, password, email, tel)
VALUES ('Yaroslav', 'Plaksiuk', 'qwerty', 'admin@example.com', '5551234567');


-- -----------------------------------------------------
-- Table `ShopInternet`.`order_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShopInternet`.`order_status` (
  `order_status_id` INT NOT NULL AUTO_INCREMENT,
  `order_status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`order_status_id`)
) ENGINE = InnoDB;

-- Додаємо необхідні статуси замовлення
INSERT INTO `ShopInternet`.`order_status` (`order_status`) VALUES
('Awaiting processing'),    -- Статус для нових замовлень, які ще не оброблені
('Accepted'),             -- Статус для замовлень, які були виконані
('Rejection');            -- Статус для замовлень, які були скасовані


-- -----------------------------------------------------
-- Table `ShopInternet`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShopInternet`.`orders` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `created_by` INT NOT NULL,
  `order_status_id` INT NOT NULL,
  `total_price` DECIMAL(10,2) NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `created_by_idx` (`created_by` ASC) VISIBLE,
  INDEX `order_status_idx` (`order_status_id` ASC) VISIBLE,
  CONSTRAINT `created_by_user`
    FOREIGN KEY (`created_by`)
    REFERENCES `ShopInternet`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `order_status`
    FOREIGN KEY (`order_status_id`)
    REFERENCES `ShopInternet`.`order_status` (`order_status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `ShopInternet`.`order_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShopInternet`.`order_items` (
  `order_item_id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`order_item_id`),
  INDEX `order_id_idx` (`order_id` ASC) VISIBLE,
  CONSTRAINT `orders`
    FOREIGN KEY (`order_id`)
    REFERENCES `ShopInternet`.`orders` (`order_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
